# Generated by Django 5.0.6 on 2024-06-25 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_bb_kind_alter_bb_price_alter_rubric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='bboard.rubric', verbose_name='Рубрика'),
        ),
    ]
