# Generated by Django 5.0.6 on 2024-09-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_alter_rubric_options_rubric_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevRubric',
            fields=[
            ],
            options={
                'ordering': ['-order', '-name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bboard.rubric',),
        ),
        migrations.AlterModelOptions(
            name='rubric',
            options={'verbose_name': 'Рубрика', 'verbose_name_plural': 'Рубрики'},
        ),
    ]
