# Generated by Django 5.0.6 on 2024-10-08 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0010_img_bb_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Img',
        ),
    ]
