# Generated by Django 5.0.6 on 2024-10-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0011_delete_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрытое'),
        ),
        migrations.AlterField(
            model_name='bb',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='order',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='Порядок'),
        ),
    ]
