# Generated by Django 5.0.6 on 2024-09-19 16:17

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.ranges
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_note'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='PGSProject2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Название')),
                ('platforms', django.contrib.postgres.fields.hstore.HStoreField(verbose_name='Использованные платформы')),
            ],
        ),
        migrations.CreateModel(
            name='PGSProject3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=40, verbose_name='Название')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PGSRoomReserving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Помещение')),
                ('reserving', django.contrib.postgres.fields.ranges.DateTimeRangeField(verbose_name='Время резервирования')),
                ('canceled', models.BooleanField(default=False, verbose_name='Отменить резервирование')),
            ],
        ),
        migrations.CreateModel(
            name='PGSRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None, verbose_name='Теги')),
            ],
        ),
    ]
